"use client";
import { useEffect, useId, useState } from "react";
import Link from "next/link";

const people = [
 {name:"Alex Morgan",initials:"AM",project:"Website redesign",hours:"7h 42m",summary:"Screenshots showed website design, content review and project-related browser activity. Later captures showed page layout updates and review in the project workspace.",tags:["Website design","Content review","Project updates"]},
 {name:"Jamie Chen",initials:"JC",project:"Marketplace operations",hours:"6h 35m",summary:"Screenshots showed product listing pages, spreadsheet updates and marketplace-related browser activity. Later captures showed listing reviews and customer support pages.",tags:["Product listings","Data entry","Customer support"]},
 {name:"Sam Taylor",initials:"ST",project:"Marketing",hours:"5h 20m",summary:"Screenshots showed campaign planning, content documents and design tools. Later captures showed edits to social content and review of campaign-related pages.",tags:["Campaign planning","Content editing","Design review"]}
];
export function AISummaryPreview(){
 const [person,setPerson]=useState(0); const [view,setView]=useState("summary"); const id=useId(); const p=people[person];
 return <div className="cm-interactive-summary"><div className="cm-demo-top"><span><i className="cm-live-dot" /> ClockMetric workspace</span><span>Interactive preview</span></div><div className="cm-demo-inner"><div className="cm-demo-title"><div><span className="cm-eyebrow">THE WORK BEHIND THE HOURS</span><h3>Daily AI summary <span>✧</span></h3></div><span className="cm-tag">Sample day</span></div><div className="cm-person-picker" aria-label="Choose sample employee">{people.map((sample,i)=><button key={sample.name} onClick={()=>setPerson(i)} aria-pressed={i===person}><span className="cm-avatar">{sample.initials}</span><span>{sample.name.split(" ")[0]}</span></button>)}</div><div className="cm-demo-metrics"><div><small>TIME TRACKED</small><strong>{p.hours}</strong></div><div><small>PROJECT</small><strong>{p.project}</strong></div></div><div className="cm-segmented" aria-label="Preview view">{["summary","records"].map(v=><button key={v} aria-pressed={view===v} aria-controls={id} onClick={()=>setView(v)}>{v==="summary"?"✧ AI summary":"▧ Work records"}</button>)}</div><div id={id} className="cm-summary-content" aria-live="polite">{view==="summary"?<><h4>{p.name}’s day, made clearer.</h4><p>Worked {p.hours} today. {p.summary}</p><div className="cm-summary-tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></>:<><h4>The context behind this example.</h4>{p.tags.map((t,i)=><div className="cm-record" key={t}><span>{["09:15","11:30","15:45"][i]}</span><b>{t}</b><span>Screenshot</span></div>)}<Link className="cm-text-link" href="/features/screenshots">Explore screenshot review ↗</Link></>}</div><div className="cm-demo-disclaimer">Illustrative data · AI describes visible activity, not work quality.</div></div></div>
}
export function TimerPreview(){
 const [running,setRunning]=useState(false); const [seconds,setSeconds]=useState(0);const [project,setProject]=useState("Website redesign");const id=useId();
 useEffect(()=>{if(!running)return;const t=setInterval(()=>setSeconds(v=>v+1),1000);return()=>clearInterval(t)},[running]);
 const time=[Math.floor(seconds/3600),Math.floor(seconds/60)%60,seconds%60].map(v=>String(v).padStart(2,"0")).join(":");
 return <div className="cm-visual"><div className="cm-mock-card cm-timer-card"><div className="cm-panel-heading"><b>ClockMetric Desktop</b><span className="cm-tag">Try the timer</span></div><label className="cm-small-label" htmlFor={id}>CURRENT PROJECT</label><select id={id} value={project} disabled={running} onChange={e=>setProject(e.target.value)}>{["Website redesign","Marketplace operations","Marketing"].map(p=><option key={p}>{p}</option>)}</select><strong className="cm-timer-digits">{time}</strong><p className="cm-timer-hint">{running?"Your demo session is running":"Ready when you are."}</p><button className="cm-button" onClick={()=>setRunning(v=>!v)}>{running?"■ Stop demo timer":"▶ Start demo timer"}</button><p className="cm-demo-disclaimer">Interactive demo only. No activity is captured.</p></div></div>
}
export function ActivityPreview(){return <div className="cm-mock-card"><div className="cm-panel-heading"><b>Activity timeline</b><span className="cm-tag">Sample day</span></div>{["09:00 – 10:00","10:00 – 11:00","11:00 – 12:00"].map((hour,i)=><details className="cm-interval" key={hour}><summary><span>◷ {hour}</span><span>4 intervals +</span></summary><p>Keyboard and mouse activity · Sample counts</p>{["00","15","30","45"].map((m,j)=><div className="cm-record" key={m}><span>{String(9+i).padStart(2,"0")}:{m}</span><b>{120+i*30+j*18} keyboard</b><span>{200+i*40+j*20} mouse</span></div>)}</details>)}<p className="cm-demo-disclaimer">Expand an hour to explore 15-minute intervals.</p></div>}
export function ScreenshotPreview(){const [selected,setSelected]=useState(0);return <div className="cm-mock-card"><div className="cm-panel-heading"><b>Screenshot review</b><span className="cm-tag">Sample captures</span></div><div className="cm-screenshot-grid">{["09:05","09:15","09:25","09:35","09:45","09:55"].map((t,i)=><button key={t} aria-pressed={selected===i} onClick={()=>setSelected(i)}><div className={`cm-mini-screen cm-screen-${i%3}`}><div className="cm-mini-toolbar"><i/><i/><i/></div><div className="cm-mini-content"><aside/><div><i/><i/><i/><i/></div></div></div><small>{t}</small></button>)}</div><div className="cm-capture-detail" aria-live="polite"><span className="cm-eyebrow">SELECTED CAPTURE · 09:{String(5+selected*10).padStart(2,"0")}</span><h3>{["Project workspace","Content document","Design review"][selected%3]}</h3><p>{["A project board with tasks organised for the day.","A content document open for editing and review.","A page layout being reviewed in a design workspace."][selected%3]}</p></div><p className="cm-demo-disclaimer">Illustrative captures, not real employee screenshots.</p></div>}
export function ReportPreview(){const [week,setWeek]=useState(0);return <div className="cm-mock-card cm-timesheet"><div className="cm-panel-heading"><b>Weekly timesheet</b><div className="cm-segmented">{["This week","Last week"].map((w,i)=><button key={w} aria-pressed={week===i} onClick={()=>setWeek(i)}>{w}</button>)}</div></div><div className="cm-timesheet-total"><div><small>TOTAL TRACKED</small><strong>{week?"35h 00m":"37h 30m"}</strong></div><span>5 working days</span></div><table><caption className="cm-sr-only">Sample weekly hours</caption><thead><tr><th>Day</th><th>Project</th><th>Tracked</th></tr></thead><tbody>{["Monday","Tuesday","Wednesday","Thursday","Friday"].map((d,i)=><tr key={d}><td>{d}</td><td>{["Design","Development","Design","Marketing","Development"][i]}</td><td>{week?"7h 00m":["8h 00m","7h 30m","8h 00m","7h 00m","7h 00m"][i]}</td></tr>)}</tbody></table><p className="cm-demo-disclaimer">Interactive report · Sample data</p></div>}
export function LeavePreview(){const [person,setPerson]=useState(0);return <div className="cm-leave-visual"><div className="cm-panel-heading"><b>Team leave</b><span className="cm-tag">Example</span></div><div className="cm-segmented">{["Jamie","Alex"].map((p,i)=><button key={p} onClick={()=>setPerson(i)} aria-pressed={person===i}>{p}</button>)}</div><div className="cm-leave-profile"><span className="cm-avatar">{person?"AM":"JC"}</span><div><b>{person?"Alex Morgan":"Jamie Chen"}</b><small>Annual leave · {person?"1 day":"2 days"}</small></div><span className="cm-status">Approved</span></div><div className="cm-calendar">{["MON","TUE","WED","THU","FRI"].map((d,i)=><div key={d} className={(person?i===2:i>2)?"cm-calendar-leave":""}><small>{d}</small><b>{21+i}</b><span>{(person?i===2:i>2)?"On leave":"Workday"}</span></div>)}</div><p className="cm-demo-disclaimer">Select a teammate to explore sample availability.</p></div>}
