"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { featureCatalog } from "@/lib/marketing";
export const loginUrl = "https://beamish-zabaione-4dcac2.netlify.app";
const links=[["AI summaries","/ai-summaries"],["How it works","/how-it-works"],["Pricing","/pricing"]];
export function SiteHeader(){const [open,setOpen]=useState(false);const [features,setFeatures]=useState(false);const ref=useRef<HTMLElement>(null);const featureButton=useRef<HTMLButtonElement>(null);const menuButton=useRef<HTMLButtonElement>(null);
 useEffect(()=>{function close(e:KeyboardEvent){if(e.key==="Escape"){if(features)featureButton.current?.focus();else if(open)menuButton.current?.focus();setOpen(false);setFeatures(false)}}function outside(e:PointerEvent){if(ref.current&&!ref.current.contains(e.target as Node)){setOpen(false);setFeatures(false)}}document.addEventListener("keydown",close);document.addEventListener("pointerdown",outside);return()=>{document.removeEventListener("keydown",close);document.removeEventListener("pointerdown",outside)}},[features,open]);
 return <header ref={ref} className="cm-header"><div className="cm-container cm-nav"><Link href="/" className="cm-logo" aria-label="ClockMetric home"><Image src="/app_icon.png" alt="" width={36} height={36} priority/>ClockMetric<span className="cm-logo-dot">.</span></Link><nav className="cm-desktop-nav" aria-label="Main navigation"><button ref={featureButton} aria-expanded={features} aria-controls="feature-navigation" onClick={()=>setFeatures(!features)}>Platform <span aria-hidden="true">⌄</span></button>{links.map(([label,href])=><Link key={label} href={href} onClick={()=>setFeatures(false)}>{label}</Link>)}</nav><div className="cm-nav-actions"><a className="cm-login" href={loginUrl}>Log in ↗</a><Link className="cm-button cm-small" href="/signup">Start free trial <span aria-hidden="true">→</span></Link><button ref={menuButton} className="cm-menu-toggle" aria-expanded={open} aria-controls="mobile-navigation" onClick={()=>setOpen(!open)} aria-label={open?"Close navigation":"Open navigation"}>{open?"✕":"☰"}</button></div></div>{features&&<div id="feature-navigation" className="cm-mega-menu"><div className="cm-container"><div className="cm-mega-intro"><p className="cm-eyebrow">YOUR WORKDAY, CONNECTED</p><h3>From hours to understanding.</h3><p>Explore the tools behind a clearer workday.</p><Link href="/#features" onClick={()=>setFeatures(false)} className="cm-text-link">Explore all features →</Link></div><div className="cm-mega-links">{featureCatalog.map(f=><Link onClick={()=>setFeatures(false)} key={f.slug} href={`/features/${f.slug}`}><span>{f.icon}</span><b>{f.name}</b></Link>)}</div></div></div>}{open&&<nav id="mobile-navigation" className="cm-mobile-nav" aria-label="Mobile navigation">{links.map(([label,href])=><Link key={label} href={href} onClick={()=>setOpen(false)}>{label}</Link>)}<details><summary>Explore all features</summary>{featureCatalog.map(f=><Link key={f.slug} href={`/features/${f.slug}`} onClick={()=>setOpen(false)}>{f.name}</Link>)}</details><a href={loginUrl}>Log in ↗</a></nav>}</header>
}
export function SiteFooter(){return <footer className="cm-footer"><div className="cm-container"><div className="cm-footer-grid"><div><Link className="cm-logo" href="/"><Image src="/app_icon.png" alt="" width={34} height={34}/>ClockMetric<span className="cm-logo-dot">.</span></Link><p>Track the time.<br/>Understand the work.<br/>Move forward together.</p><Link className="cm-text-link" href="/signup">Your 14-day trial starts here →</Link></div><div><h3>Track & understand</h3>{featureCatalog.slice(0,6).map(f=><Link key={f.slug} href={`/features/${f.slug}`}>{f.name}</Link>)}</div><div><h3>Manage your team</h3>{featureCatalog.slice(6).map(f=><Link key={f.slug} href={`/features/${f.slug}`}>{f.name}</Link>)}</div><div><h3>Get started</h3><Link href="/pricing">Pricing</Link><Link href="/how-it-works">How it works</Link><Link href="/#faq">Your questions, answered</Link><Link href="/signup">Create your workspace</Link><a href={loginUrl}>Log in ↗</a></div></div><div className="cm-footer-bottom"><span>© {new Date().getFullYear()} ClockMetric. All rights reserved.</span><span>Remote teams. Real work. Clearer days.</span><a href="#main-content">Back to top ↑</a></div></div></footer>}
export function FinalCTA(){return <section className="cm-final-cta"><div className="cm-container"><p className="cm-eyebrow">A CLEARER WORKDAY STARTS HERE</p><h2>Less catching up.<br/>More moving forward.</h2><p>Bring your team’s time and work into focus with ClockMetric.</p><Link className="cm-button" href="/signup">Start your 14-day free trial →</Link><small>A$10 per active employee/month after your trial.</small></div></section>}
