export const featureCatalog = [
 {slug:"daily-ai-summaries",name:"AI work summaries",icon:"✧",headline:"A whole workday. A few clear paragraphs.",description:"Turn captured work activity into a readable daily overview. Catch up on what was visible, then explore the records whenever you need more context.",benefits:["Start your review with the story behind the hours","Bring observable work into everyday team conversations","Keep original screenshots and time records in reach"],steps:["Employees track their work against a project.","Captured screenshots provide visible work context.","Read the AI summary alongside time and activity records."],question:"Does an AI summary replace reviewing the work?",answer:"No. Summaries describe observable activity and can miss context. Use them as a starting point, alongside original records and conversations with your team."},
 {slug:"time-tracking",name:"Employee time tracking",icon:"◷",headline:"Give every hour a place to belong.",description:"Choose a project, start the desktop timer and get into the work. ClockMetric keeps recorded hours connected to the project behind them.",benefits:["A simple start and stop workflow for employees","Project context attached to every work session","Recorded hours ready for timesheets and weekly reviews"],steps:["Select the project you are working on.","Start the Windows desktop timer.","Stop your session and review the recorded time."],question:"Do admins need to start a timer?",answer:"No. Employees track time in the desktop app. Admins manage their workspace and review team activity in the web dashboard."},
 {slug:"screenshots",name:"Automatic screenshots",icon:"▧",headline:"See the context behind the clock.",description:"Automatic and random screenshots give recorded work sessions a visual record. Review captures by employee and hour without losing track of the day.",benefits:["Work-session captures organised for easy review","Hourly groups keep the timeline manageable","Visual context that supports AI work summaries"],steps:["An employee starts a tracked work session.","Screenshots are captured during the active session.","Open the grouped timeline to review visible work."],question:"Are screenshots taken throughout the entire day?",answer:"Screenshots are captured during tracked sessions while the employee timer is running. Explain the tracking workflow to your team before they begin."},
 {slug:"keyboard-activity",name:"Keyboard & activity",icon:"⌁",headline:"Put work patterns into perspective.",description:"Review keyboard and mouse activity intervals alongside recorded time. Compact hourly groups help you explore the day without an overwhelming wall of data.",benefits:["15-minute activity intervals","Expandable hourly groups","More context alongside screenshots and time"],steps:["Activity is measured while time is being tracked.","Intervals are organised into hourly groups.","Review the patterns with the related work records."],question:"Does activity alone measure productivity?",answer:"No. Activity counts provide context, but do not measure work quality or completed outcomes. Review them alongside project work and team conversations."},
 {slug:"projects",name:"Project management",icon:"▤",headline:"Keep people, projects and time connected.",description:"Create a home for the work your team does. Project-based tracking brings structure to daily sessions and clarity to your weekly review.",benefits:["Projects organised inside your workspace","Employee hours attached to the right work","Project totals for a more informed review"],steps:["Create projects for your team.","Employees select a project when tracking.","Review recorded hours by project."],question:"Can employees track different projects?",answer:"Yes. Employees select the relevant project before starting a session, keeping each recorded session connected to the right work."},
 {slug:"reports",name:"Timesheets & reports",icon:"▥",headline:"Daily details. Weekly perspective.",description:"Bring tracked hours into an organised view by employee and project. Go into your weekly check-in with a clear record of where time went.",benefits:["Daily and weekly time totals","Employee and project breakdowns","AI summaries add readable context to the numbers"],steps:["Your team records project-based work sessions.","Tracked hours are grouped into timesheets and reports.","Review totals together with AI work summaries."],question:"Can I see time by employee and project?",answer:"Yes. ClockMetric organises tracked time around employees and projects, helping admins review the working week from both perspectives."},
 {slug:"admin-dashboard",name:"Web admin dashboard",icon:"▦",headline:"Your whole team. One clear view.",description:"See working and offline status, recorded hours and project totals in your browser. Move from an overview to the details that deserve your attention.",benefits:["Working and offline employee status","Connected employee and project views","Access through a browser on Windows or Mac"],steps:["Sign in to your workspace as an admin.","Review team status and tracked hours.","Explore employee records and AI work summaries."],question:"Does the admin dashboard work on a Mac?",answer:"Admins can use the web dashboard in their browser on a Mac or Windows computer. The employee desktop tracker described here is for Windows."},
 {slug:"leave-management",name:"Leave management",icon:"☼",headline:"Plan the week around your people.",description:"Bring leave into the same workspace as working time. Keep a clearer picture of team availability as you plan the days ahead.",benefits:["Employee leave in your team workspace","Availability alongside the working week","Less switching between separate team records"],steps:["Review employee leave in your workspace.","Check the dates and leave status.","Use availability to inform your team planning."],question:"Is leave management included in the plan?",answer:"Yes. Leave management is part of the ClockMetric platform described in the A$10 per active employee/month plan."},
 {slug:"employee-management",name:"Employee management",icon:"♙",headline:"A connected workspace for every teammate.",description:"Keep your employees and their tracked work organised in one place. Give admins a clearer view of the people behind each project.",benefits:["Employees organised by workspace","Time and activity connected to each employee","Working and offline status for daily visibility"],steps:["Set up your workspace and add your employees.","Organise the projects your team works on.","Review employee time, activity and summaries."],question:"What does ClockMetric cost for 10 active employees?",answer:"At A$10 per active employee per month, 10 active employees cost A$100 per month. Start with a 14-day free trial."},
 {slug:"desktop-tracker",name:"Desktop employee tracker",icon:"▣",headline:"Start your session. Stay with your work.",description:"A Windows desktop tracker for employees, connected to a browser dashboard for admins. One straightforward workflow from the first timer to the daily summary.",benefits:["Windows desktop tracking","Project selection before starting work","Connected screenshots, activity and time records"],steps:["Create your account and set up your workspace.","Install the Windows employee tracker.","Choose a project and start a work session."],question:"Is there a Mac employee desktop app?",answer:"This website describes the Windows employee tracker. Mac users can access the web admin dashboard; a Mac desktop tracker is not offered on this page."},
] as const;
export type FeatureSlug = typeof featureCatalog[number]["slug"];
export const faqs = [
 ["What is ClockMetric?","An employee time-tracking platform for remote teams. ClockMetric connects project hours, screenshots, keyboard activity, timesheets, AI work summaries and team management in one workspace."],
 ["How do AI work summaries help?","They turn visible work context into a readable overview, so admins can start with the summary and open the original records when they need more detail."],
 ["What is included in the 14-day trial?","Create your workspace and explore the ClockMetric workflow with your employees and projects for 14 days. Ongoing pricing is A$10 per active employee per month."],
 ["How much does ClockMetric cost?","A$10 per active employee per month. For example, 10 active employees cost A$100 per month. Use the calculator above to estimate your team’s monthly cost."],
 ["Who uses the desktop app and the web dashboard?","Employees use the Windows desktop app to track work. Admins review hours, screenshots, activity and summaries in the web dashboard, accessible from a Windows or Mac browser."],
 ["When are screenshots and activity recorded?","During tracked work sessions while the employee timer is running. Screenshots and 15-minute activity intervals provide context alongside recorded hours."],
 ["Can I manage projects, employees and leave?","Yes. ClockMetric brings these together in your workspace, alongside timesheets, weekly reports and working/offline status."],
 ["Should I treat AI summaries as a final assessment?","No. AI summaries describe visible activity, and may miss context. Review original records and discuss work with your team before drawing conclusions."]
];
